# Site settings
title: Alok Shrestha
description: >- # this means to ignore newlines until "baseurl:"
  Always code as if the guy who ends up maintaining your code
  will be a violent psychopath who knows where you live.
baseurl: "/blog"  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: aalooksth


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Alok Shrestha
  image    : https://scontent.fktm7-1.fna.fbcdn.net/v/t1.0-9/30743839_1646365012127528_3593150106322337792_n.jpg?_nc_cat=104&_nc_ht=scontent.fktm7-1.fna&oh=86e64daab7d50700f6fc0511051258e8&oe=5D38930E
  email    : aalooksth@gmail.com
  github   : aalooksth
  twitter  : aalooksth
  linkedin : aalooksth
  facebook : aalooksth


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
